version: 2

workflows:
  version: 2
  build-and-release:
    jobs:
    - build

jobs:
  build:
    docker:
    - image: circleci/node:12
    steps:
    - checkout
    - run: npm ci
    - run: npm run test
    - run:
        name: Install gcloud
        command: |
          curl https://sdk.cloud.google.com | CLOUDSDK_CORE_DISABLE_PROMPTS=true bash
          echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
          source $BASH_ENV
          echo $GCS_KEY | base64 --decode > gcs_key.json
          gcloud auth activate-service-account --key-file gcs_key.json
    - run:
        name: build and upload to gcs to be able to download and test
        command: |
          if [ -z "$CIRCLE_PR_NUMBER" ]; then
            BUILD_TARGET=review npm run build
            BUILD_EXTENSION_TYPE=personal npm run pack:chrome
            BUILD_EXTENSION_TYPE=teams npm run pack:chrome
            ./node_modules/.bin/web-ext sign -a build/personal -s dist/personal/firefox --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET
            ./node_modules/.bin/web-ext sign -a build/teams -s dist/teams/firefox --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET
            ./script/build_and_upload_branch
          fi
