version: 2

workflows:
  version: 2

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    matrix:
        platform: [ubuntu-latest, windows-latest]
        node-version: [12.x, 14.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.platform }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci, test and pack
      run: |
        npm ci
        npm run test
        npm run pack

  upload:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npm test
    - run:
        name: Install gcloud
        command: |
          curl https://sdk.cloud.google.com | CLOUDSDK_CORE_DISABLE_PROMPTS=true bash
          echo 'source ~/google-cloud-sdk/path.bash.inc' >> $BASH_ENV
          source $BASH_ENV
          echo $GCS_KEY | base64 --decode > gcs_key.json
          gcloud auth activate-service-account --key-file gcs_key.json
    - run:
        name: build and upload to gcs to be able to download and test
        command: |
          if [ -z "$CIRCLE_PR_NUMBER" ]; then
            BUILD_TARGET=review npm run build
            BUILD_EXTENSION_TYPE=personal npm run pack:chrome
            BUILD_EXTENSION_TYPE=teams npm run pack:chrome
            ./node_modules/.bin/web-ext sign -a build/personal -s dist/personal/firefox --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET
            ./node_modules/.bin/web-ext sign -a build/teams -s dist/teams/firefox --api-key $AMO_API_KEY --api-secret $AMO_API_SECRET
            ./script/build_and_upload_branch
          fi
