name: Build and Packaging Check

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
          platform: [ubuntu-latest, windows-latest]
          node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.platform }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      id: cache
      uses: actions/cache@v2.0.0
      with:
        path: node_modules
        key: ${{ runner.os }}-node-v2-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
        restore-keys: |
          ${{ runner.os }}-node-v2-
    - run: npm ci
      if: steps.cache.outputs.cache-hit != 'true'
    - run: npm run test
    - run: npm run pack
